# Generated by Django 5.2.13 on 2026-04-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gasoil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='matricule_voiture',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
