# Generated by Django 5.2.13 on 2026-04-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gasoil_user_matricule_voiture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gasoil',
        ),
        migrations.AddField(
            model_name='user',
            name='gasoil_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gasoil mensuel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='matricule_voiture',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricule voiture'),
        ),
    ]
