# Generated by Django 5.2.13 on 2026-04-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rechargegasoil'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lien_drive',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien Google Drive'),
        ),
    ]
