# Generated by Django 5.2.13 on 2026-04-22 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interventions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Constat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('poteau_endommage', 'Poteau endommagé'), ('client_absent', 'Client absent'), ('acces_refuse', 'Accès refusé'), ('travaux_termines', 'Travaux terminés'), ('probleme_technique', 'Problème technique'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('horodatage_photo', models.DateTimeField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/%d/')),
                ('nom_signataire', models.CharField(blank=True, max_length=100)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constats', to='interventions.intervention')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
