# Generated by Django 5.2.13 on 2026-04-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constats', '0001_initial'),
        ('interventions', '0002_operateur_statutintervention_typeintervention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constat',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constats', to='interventions.intervention'),
        ),
    ]
