# Generated by Django 5.2.13 on 2026-04-22 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constats', '0002_alter_constat_intervention'),
        ('interventions', '0002_operateur_statutintervention_typeintervention_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constat',
            options={},
        ),
        migrations.AddField(
            model_name='constat',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='constat',
            name='est_signe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='constat',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='constats_pdf/'),
        ),
        migrations.AlterField(
            model_name='constat',
            name='categorie',
            field=models.CharField(choices=[('litige_client', 'Litige client'), ('litige_operateur', 'Litige opérateur'), ('probleme_materiel', 'Problème matériel'), ('incident_terrain', 'Incident terrain'), ('client_absent', 'Client absent'), ('acces_refuse', 'Accès refusé'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='constat',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interventions.intervention'),
        ),
        migrations.AlterField(
            model_name='constat',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constat',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='constats/'),
        ),
        migrations.AlterField(
            model_name='constat',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='constat',
            name='technicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PhotoConstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='constats_photos/')),
                ('type_photo', models.CharField(choices=[('avant', 'Avant intervention'), ('apres', 'Après intervention')], max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('horodatage_photo', models.DateTimeField(auto_now_add=True)),
                ('constat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='constats.constat')),
            ],
        ),
    ]
