# Generated by Django 5.2.13 on 2026-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constats', '0003_alter_constat_options_constat_date_modification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constat',
            name='commentaire_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='constat',
            name='date_soumission',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constat',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide', 'Validé par admin'), ('rejete', 'Rejeté')], default='brouillon', max_length=20),
        ),
    ]
