# Generated by Django 5.2.13 on 2026-04-22 09:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bareme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_prestation', models.CharField(max_length=100)),
                ('tarif_technicien', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tarif_operateur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_intervention', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('bareme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='interventions.bareme')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_intervention'],
            },
        ),
    ]
