# Generated by Django 5.2.13 on 2026-04-22 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Opérateur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='StatutIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Statut',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': "Type d'intervention",
                'ordering': ['nom'],
            },
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='bareme',
        ),
        migrations.RenameField(
            model_name='intervention',
            old_name='notes',
            new_name='commentaire',
        ),
        migrations.AddField(
            model_name='intervention',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='intervention',
            name='operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interventions.operateur'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interventions.statutintervention'),
        ),
        migrations.CreateModel(
            name='BaremeTechnicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('type_intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bareme_technicien', to='interventions.typeintervention')),
            ],
            options={
                'verbose_name': 'Barème technicien',
            },
        ),
        migrations.CreateModel(
            name='BaremeOperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baremes', to='interventions.operateur')),
                ('type_intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baremes_operateurs', to='interventions.typeintervention')),
            ],
            options={
                'verbose_name': 'Barème opérateur',
                'unique_together': {('type_intervention', 'operateur')},
            },
        ),
        migrations.AddField(
            model_name='intervention',
            name='type_intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interventions.typeintervention'),
        ),
        migrations.DeleteModel(
            name='Bareme',
        ),
    ]
